report test results

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -15,7 +15,7 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-    - name: Set up JDK 12
+    - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         java-version: '21'
@@ -26,5 +26,16 @@ jobs:
       with:
         gradle-version: '8.10'
 
-    - name: Build with Gradle Wrapper
+    - name: Build
+      run: gradle build
+
+    - name: Unit Test
       run: gradle test
+
+    - name: Report Test Results
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Unit Test          # Name of the check run which will be created
+        path: build/test-results/TEST-*.xml    # Path to test results
+        reporter: jest-junit
